/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ugovor.view;

import com.spire.doc.Document;
import com.spire.doc.FileFormat;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import ugovor.model.Korisnik;
import static ugovor.util.SearchDatabase.searchDatabase;

/**
 *
 * @author Lorena
 */
public class Pretraga extends javax.swing.JFrame {

    /**
     * Creates new form Pretraga
     */
    public Pretraga() {
        initComponents();
        setTitle("Pretraga i upis dokumenta");
       // populateComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUnos = new javax.swing.JTextField();
        btnPretraga = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstLista = new javax.swing.JList<>();
        btnPohrani = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cBoxUgovori = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtUnos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUnosKeyPressed(evt);
            }
        });

        btnPretraga.setText("Pretraži");
        btnPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaActionPerformed(evt);
            }
        });
        btnPretraga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPretragaKeyPressed(evt);
            }
        });

        jScrollPane1.setViewportView(lstLista);

        btnPohrani.setText("Pohrani u ugovor");
        btnPohrani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPohraniActionPerformed(evt);
            }
        });

        jLabel1.setText("Korisnik");

        cBoxUgovori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ugovorPotpora", "ugovorSport" }));
        cBoxUgovori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxUgovoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtUnos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnPretraga)))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPohrani, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(cBoxUgovori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPretraga)
                            .addComponent(cBoxUgovori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPohrani, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaActionPerformed
        lstLista.clearSelection();
        DefaultListModel<String> model = new DefaultListModel<>();
        JList<String> list = new JList<>(model);
        String s = txtUnos.getText();
        // String upit = "ime";
        ArrayList<Korisnik> marija = new ArrayList<Korisnik>(searchDatabase(s));
        if (marija.size() == 0) {
            JOptionPane.showMessageDialog(null, "Nema trazenog korisnika");
        }
        for (Korisnik k : marija) {
            model.addElement(k.getIme() + " " + k.getPrezime() + " " + k.getOIB());
            lstLista.setModel(model);
            // txtRez.setText(k.getIme() + " " + k.getPrezime() + "\n");
        }


    }//GEN-LAST:event_btnPretragaActionPerformed

    private void btnPohraniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPohraniActionPerformed

        //  DefaultListModel<String> model = new DefaultListModel<>();
        // JList<String> list = new JList<>( model );
        //  String selectedItem = lstLista.getSelectedValue();
        String selectedItem = lstLista.getSelectedValue();
        String[] words = selectedItem.split("\\s");
        selectedItem = words[2];

        // Query the database for the name corresponding to the selected item
        String upit = "OIB";
        ArrayList<Korisnik> odabrano = new ArrayList<Korisnik>(searchDatabase(selectedItem, upit));

        for (Korisnik k : odabrano) {
            Document document = new Document("C:\\Users\\" + System.getProperty("user.name") + "\\Ugovori\\ugovoriTemplate\\" + cBoxUgovori.getSelectedItem().toString() + ".docx");

            // Replace a specific text
            document.replace("<ime>", k.getIme(), false, true);
            document.replace("<prezime>", k.getPrezime(), false, true);
            document.replace("<adresa>", k.getUlica(), false, true);
            document.replace("<iban>", k.getIBAN(), false, true);
            document.replace("<email>", k.getEmail(), false, true);
            document.replace("<kucniBroj>", k.getKucniBroj(), false, true);
            document.replace("<oib>", k.getOIB(), false, true);

            //Save the result document
            document.saveToFile("C:\\Users\\" + System.getProperty("user.name") + "\\Ugovori\\" + k.getIme() + k.getPrezime() + ".docx", FileFormat.Docx);
            // txtPoruka.setText(k.getKucniBroj()); }

            JOptionPane.showMessageDialog(null, "Ugovor uspješno popunjen!");

        }
                    
                    

                

                
//            }
        

//            lstLista.addMouseListener(new MouseAdapter() {
//         public void mouseClicked(MouseEvent me) {
//            if (me.getClickCount() == 1) {
//               JList target = (JList)me.getSource();
//               int index = target.locationToIndex(me.getPoint());
//               if (index >= 0) {
//                  Object item = target.getModel().getElementAt(index);
//                   JOptionPane.showMessageDialog(null, item.toString());
//               }
//            }
//         }
//      });

    }//GEN-LAST:event_btnPohraniActionPerformed

    private void btnPretragaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPretragaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPretragaKeyPressed

    private void txtUnosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            lstLista.clearSelection();
            DefaultListModel<String> model = new DefaultListModel<>();
            JList<String> list = new JList<>(model);
            String s = txtUnos.getText();
            // String upit = "ime";
            ArrayList<Korisnik> marija = new ArrayList<Korisnik>(searchDatabase(s));
            for (Korisnik k : marija) {
                model.addElement(k.getIme() + " " + k.getPrezime() + " " + k.getOIB());
                lstLista.setModel(model);
                // txtRez.setText(k.getIme() + " " + k.getPrezime() + "\n");
            }
        }
    }//GEN-LAST:event_txtUnosKeyPressed

    private void cBoxUgovoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxUgovoriActionPerformed

    cBoxUgovori.getSelectedItem();
        
    }//GEN-LAST:event_cBoxUgovoriActionPerformed

    /**
     * @param args the command line arguments
     */
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPohrani;
    private javax.swing.JButton btnPretraga;
    private javax.swing.JComboBox<String> cBoxUgovori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstLista;
    private javax.swing.JTextField txtUnos;
    // End of variables declaration//GEN-END:variables
}
