/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ugovor.view;

/**
 *
 * @author Korisnik
 */
public class Test extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    public Test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtPolje = new javax.swing.JTextArea();
        comboIzaberi = new javax.swing.JComboBox<>();
        btnDohvati = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtPolje.setColumns(20);
        txtPolje.setRows(5);
        jScrollPane1.setViewportView(txtPolje);

        comboIzaberi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "izaberi", "dokument1", "dokument2" }));
        comboIzaberi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboIzaberiActionPerformed(evt);
            }
        });

        btnDohvati.setText("Dohvati");
        btnDohvati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDohvatiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboIzaberi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDohvati, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboIzaberi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDohvati)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboIzaberiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboIzaberiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboIzaberiActionPerformed

    private void btnDohvatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDohvatiActionPerformed
        String itemText = (String)comboIzaberi.getSelectedItem( );
        if(itemText.equals("dokument1")){
        txtPolje.setText("MINISTARSTVO TURIZMA I SPORTA, Prisavlje 14, 10000 Zagreb, OIB: 87892589782,  \n" +
"\n" +
"koje zastupa ministrica dr.sc. Nikolina Brnjac (u daljnjem tekstu: Ministarstvo)  \n" +
"\n" +
"I <ime> <prezime>, <adresa> <kucniBroj>, OIB <oib> (u daljnjem tekstu: Korisnik),  \n" +
"\n" +
"zaključili su dana <datumUgovora> 2022. godine \n" +
"\n" +
" \n" +
"\n" +
"U G O V O R br. <brojUgovora> \n" +
"\n" +
"o sufinanciranju projekata udruga u turizmu u 2022.  \n" +
"\n" +
" \n" +
"\n" +
"Članak 1. \n" +
"\n" +
"Na temelju provedenog Javnog natječaja za sufinanciranje projekata udruga u turizmu  \n" +
"\n" +
"u 2022. i Odluke o odabiru projekata udruga temeljem Javnog natječaja za sufinanciranje  \n" +
"\n" +
"projekata udruga u turizmu u 2022. godini, Ministarstvo će isplatiti Korisniku na teret  \n" +
"\n" +
"sredstava osiguranih u Državnom proračunu za 2022. godinu, na razdjelu 090 Ministarstva \n" +
"\n" +
" u glavi 05 pod šifrom P3208 aktivnost 587014, konto 3811 – Tekuće donacije u novcu iznos od  \n" +
"\n" +
" \n" +
"<cijena>  kuna  \n" +
"\n" +
" \n" +
"(slovima: <cijenaSlovima>) \n" +
"\n" +
" \n" +
"\n" +
"za financijsku potporu projekta pod nazivom \n" +
"\n" +
"„ <nazivProjekta> “ \n" +
"\n" +
" \n" +
"s rokom izvršenja prema prijavi projekta, a najkasnije do <datumNajkasnije> 2022. godine. \n" +
"\n" +
" \n" +
"Članak 2. \n" +
"\n" +
"Sredstva iz članka 1. ovog ugovora mogu se koristiti isključivo za provedbu projekta sukladno \n" +
"\n" +
" uvjetima Javnog natječaja i prema Obrascu proračuna projekta u 2022. godini, koji je sastavni  \n" +
"\n" +
"dio ovog ugovora. \n" +
"\n" +
" \n" +
"\n" +
"Članak 3. \n" +
"\n" +
"Dostavljeni Obrazac opisa projekta i Obrazac proračuna projekta s pripadajućom dokumentacijom \n" +
"\n" +
" koju je Korisnik dostavio prijavljujući se na Javni natječaj, sastavni su dio ovog ugovora. \n" +
"\n" +
" \n" +
"\n" +
"Članak 4.  \n" +
"\n" +
"Ministarstvo će sredstva iz članka 1. ovog ugovora isplatiti na žiroračun Korisnika IBAN <iban>, \n" +
"\n" +
" u dva dijela: 50% iznosa sredstava po potpisivanju ugovora, a 50% sredstava po dostavljenom  \n" +
"\n" +
"Privremenom izvješću iz članka 5. ovoga ugovora. \n" +
"\n" +
" \n" +
"\n" +
"Članak 5.  \n" +
"\n" +
"Radi kontrole namjenskog korištenja sredstava Korisnik se obvezuje da će Ministarstvu  \n" +
"\n" +
"dostaviti Privremeno izvješće (na propisanom obrascu) o tijeku provedbe projekta..  \n" +
"\n" +
" \n" +
"\n" +
"Korisnik podnosi završno Izvješće o izvršenju. Izvješće se podnosi na propisanim obrascima  \n" +
"\n" +
"Ministarstva: \n" +
"\n" +
"a)Obrazac opisnog izvještaja (na propisanom obrascu, ispunjenom na računalu) u papirnatom \n" +
"\n" +
" obliku i elektroničkom obliku (CD/USB i sl.)   \n" +
"\n" +
" \n" +
"b)Obrazac financijskog izvještaja (na propisanom obrascu, ispunjenom na računalu) u  \n" +
"\n" +
"papirnatom i elektroničkom obliku (CD/USB i sl.) uz detaljno dokumentiranje ukupnih troškova projekta: \n" +
"\n" +
"•za bezgotovinska plaćanja - preslike računa (R1 ili R2) koji glase na Korisnika  \n" +
"\n" +
"te pripadajući izvod \n" +
"\n" +
"•za gotovinska plaćanja - preslike računa (R1 ili R2) koji glase na Korisnika, preslike  \n" +
"\n" +
"isplatnica iz blagajne i blagajničkog izvješća \n" +
"\n" +
"•ostalu dokumentaciju – preslike putnih naloga s pripadajućim prilozima, preslike  \n" +
"\n" +
"dokumenata na temelju kojih su obavljana plaćanja (ugovori, sporazumi, obračuni honorara) i sl.  \n" +
"\n" +
"•priloge vezane uz provedbu projekta (listu sudionika, program provedbe aktivnosti i dr. \n" +
"\n" +
" \n" +
"c)obrazac s podacima o stavkama nastalih troškova u razdoblju obuhvaćenom izvještajem  \n" +
"\n" +
"(za svaku stavku potrebno je navesti naslov, iznos, relevantno proračunsko poglavlje projekta  \n" +
"\n" +
"i poziv na dokument  kojim se trošak opravdava te broj izvoda o izvršenim plaćanjima) \n" +
"\n" +
" \n" +
"d)obrazac s opisom svih odstupanja u izvorima financiranja u odnosu na prijedlog koji je odobren \n" +
"\n" +
" \n" +
"\n" +
"Članak 6. \n" +
"\n" +
"Ministarstvo pridržava pravo kontinuiranog praćenja i vrednovanja izvršenja projekta Korisnika  \n" +
"\n" +
"iz članka 1. ovog ugovora, te preispitivanje financija i troškova u bilo koje vrijeme trajanja  \n" +
"\n" +
"sufinanciranja te u razdoblju od 3 godine nakon završetka projekta. \n" +
"\n" +
" \n" +
"Ministarstvo može neposrednu kontrolu iz prethodnog stavka ovog ugovora obaviti u prostorijama  \n" +
"\n" +
"Korisnika, te je o namjeri izvršenja neposredne kontrole dužan prethodno obavijestiti Korisnika  \n" +
"\n" +
"barem tri dana prije planiranog izvršenja kontrole. \n" +
"\n" +
" \n" +
"Korisnik je obavezan o datumu i mjestu održavanja projektnih aktivnosti  \n" +
"\n" +
"(seminari, radionice, sajmovi …) obavijestiti Ministarstvo najkasnije 15 dana prije održavanja,  \n" +
"\n" +
"kako bi se, po potrebi, mogao obaviti nadzor očevidom. \n" +
"\n" +
" \n" +
"\n" +
"Članak 7.  \n" +
"\n" +
"Korisnik ovlašćuje Ministarstvo da radi nadzora namjenskog korištenja sredstava iz članka 1.  \n" +
"\n" +
"ovog ugovora neposredno kontaktira sve pravne i fizičke osobe kojima je prema priloženoj  \n" +
"\n" +
"dokumentaciji Korisnik isplatio novčana sredstva koja je dobio od Ministarstva u ime financijske potpore. \n" +
"\n" +
" \n" +
"Davatelj će prikupljene podatke pravnih i fizičkih osoba iz članka 6., stavak 1. koristiti  \n" +
"\n" +
"isključivo u svrhu kontinuiranog (financijskog) praćenja i vrednovanja projekta i sukladno  \n" +
"\n" +
"Uredbi (EU) 2016/679 Europskog parlamenta i Vijeća o zaštiti pojedinaca u vezi s obradom osobnih  \n" +
"\n" +
"podataka i o slobodnom kretanju takvih podataka te Zakonu o provedbi Opće uredbe o zaštiti podataka  \n" +
"\n" +
"(NN 42/2018). \n" +
"\n" +
" \n" +
"\n" +
"Članak 8.\n" +
"\n" +
"Korisnik se obvezuje pravodobno izvijestiti Ministarstvo o eventualnim objektivnim smetnjama tijekom  \n" +
"\n" +
"realizacije projekta koje onemogućuju ili bitno mijenjaju opseg, vrstu planiranih aktivnosti i/ili  \n" +
"\n" +
"korisnika projekta, izvršenje projekta u ugovorenom roku ili izvršenje projekta u planiranim stavkama  \n" +
"\n" +
"proračuna, kako bi se mogle ugovoriti izmjene ugovornih obveza. \n" +
"\n" +
" \n" +
"Manje izmjene ugovora mogu biti: \n" +
"\n" +
"-izmjene proračuna između proračunskih poglavlja manje od 15%, \n" +
"\n" +
"-zamjena člana tima, \n" +
"\n" +
"-promjena bankovnog računa korisnika, \n" +
"\n" +
"-promjena adrese ili drugih kontakata korisnika, \n" +
"\n" +
"-male promjene projekta koje ne utječu na njegov opseg i ciljeve  \n" +
"\n" +
"(npr. manje promjene u vremenskom rasporedu provedbe aktivnosti). \n" +
"\n" +
" \n" +
"\n" +
"Manje izmjene ugovora mogu biti jednostrane, te ne zahtijevaju izradu Dodatka ugovoru. \n" +
"\n" +
"Veće izmjene ugovora su:  \n" +
"\n" +
"-izmjene proračuna između proračunskih poglavlja veće od 15%, \n" +
"\n" +
"-produženje trajanja provedbe projekta (maksimalno do 6 mjeseci), \n" +
"\n" +
"-dodatak novih aktivnosti u projekt, \n" +
"\n" +
"-promjena projektnih aktivnosti koja značajno utječe na opseg i ciljeve. \n" +
"\n" +
"Veće izmjene ugovora zahtijevaju izradu Dodatka ugovoru i njegovo potpisivanje od strane davatelja \n" +
"\n" +
" i korisnika. Davatelj odlučuje kod svake obavijesti radi li se o manjoj ili većoj izmjeni i  \n" +
"\n" +
"sukladno tome odlučuje je li potrebno izraditi Dodatak ugovoru. \n" +
"\n" +
" \n" +
"\n" +
"Članak  9. \n" +
"\n" +
"Izmjene ugovornih obveza Korisnik može zatražiti najkasnije do  \n" +
"\n" +
"<datumIzmjene> 2023. godine odnosno 30 dana prije isteka roka izvršenja projekta. Svaka izmjena  \n" +
"\n" +
"ugovornih obveza treba biti zatražena i odobrena u pisanom obliku. \n" +
"\n" +
" \n" +
"Korisnik ne može zatražiti izmjene u provedbi projekta, produljenje roka provedbe ili prenamjenu  \n" +
"\n" +
"pojedinih stavki proračuna nakon navedenog roka iz stavka 1. ovog članka. \n" +
"\n" +
" \n" +
"Zahtjev za prenamjenu dijela sredstava i/ili zahtjev za produženje roka provedbe projekta Korisnik \n" +
"\n" +
" dostavlja Ministarstvu u pisanom obliku s obrazloženjem i s prijedlogom novog obrasca proračuna  \n" +
"\n" +
"provedbe projekta. \n" +
"\n" +
" \n" +
"Ministarstvo ima pravo ne odobriti prenamjenu dijela sredstava i/ili produženje roka provedbe  \n" +
"\n" +
"projekta ukoliko se time bitno mijenja sadržaj i priroda projekta ili ako zahtjev nema utemeljenje  \n" +
"\n" +
"u objektivnim razlozima za prenamjenu i/ili produženje roka provedbe projekta. \n" +
"\n" +
" \n" +
"\n" +
"Članak 10. \n" +
"\n" +
"U svrhu osiguranja povrata odobrenih sredstava, Korisnik će prilikom potpisivanja ovoga ugovora  \n" +
"\n" +
"priložiti bjanko zadužnicu solemniziranu od javnog bilježnika na prvi veći iznos od ugovorenog  \n" +
"\n" +
"iznosa sredstava.  \n" +
"\n" +
" \n" +
"Instrument osiguranja plaćanja iz stavka 1. ovoga članka Ministarstvo zadržava do izvršenja  \n" +
"\n" +
"obveza iz ovoga ugovora. \n" +
"\n" +
" \n" +
"\n" +
"Članak 11. \n" +
"\n" +
"Ako Ministarstvo utvrdi da je Korisnik nenamjenski koristio sredstva financijske potpore za  \n" +
"\n" +
"izvršenje projekta iz članka 1. ovog ugovora ili nije izvršio projekt u ugovorenom roku,  \n" +
"\n" +
"ako nije podnio odgovarajuća izvješća u roku i sa sadržajem određenim u članku 5. ovog  \n" +
"\n" +
"ugovora ili ako Ministarstvu ne omogući nadzor nad namjenskim korištenjem sredstava financijske \n" +
"\n" +
" potpore  iz članka 6. i članka 7. ovog ugovora, Korisnik je dužan vratiti primljena nenamjenski  \n" +
"\n" +
"utrošena ili neutrošena sredstva uz obračunate kamate u roku od 30 dana od dana primitka zahtjeva  \n" +
"\n" +
"Ministarstva za povrat zaprimljenih sredstava. \n" +
"\n" +
" \n" +
"U slučaju da Korisnik ne postupi u skladu sa zahtjevom iz stavka 1. ovoga članka, Ministarstvo \n" +
"\n" +
" će aktivirati instrument osiguranja plaćanja iz članka 10. ovoga ugovora. \n" +
"\n" +
" \n" +
"\n" +
"Članak 12.  \n" +
"\n" +
"Ministarstvo i Korisnik preuzimaju obvezu čuvanja svih dokumenata, podataka ili drugih  \n" +
"\n" +
"relevantnih materijala dostavljenih u provedbi projekta najmanje sedam godina od posljednje uplate sredstava. \n" +
"\n" +
" \n" +
"\n" +
"Članak 13.  \n" +
"\n" +
"Ako Ministarstvo utvrdi da Korisnik nije ispunio ugovorne obveze, uskratit će pravo na financijsku \n" +
"\n" +
" potporu projekata i programa Korisnika u sljedeće dvije godine. \n" +
"\n" +
" \n" +
"\n" +
"Članak 14. \n" +
"\n" +
"Korisnik se obvezuje na svim tiskanim, video i drugim materijalima vezanim uz projekt istaknuti \n" +
"\n" +
" logotip i naziv Ministarstva kao institucije koja sufinancira projekt koji je predmet ovog ugovora \n" +
"\n" +
" te logotip pristupačnog turizma Ministarstva. \n" +
"\n" +
" \n" +
"Korisnik je suglasan da Ministarstvo koristi i objavljuje dostavljene mu fotografije, video i audio  \n" +
"\n" +
"zapise iz stavka 1. ovog članka u cilju promocije financijskih potpora, ilustracije razvoja civilnoga \n" +
"\n" +
" društva u Republici Hrvatskoj i djelovanja Ministarstva. \n" +
"\n" +
" \n" +
"\n" +
"Članak 15. \n" +
"\n" +
"Ministarstvo ne snosi odgovornost, neposrednu ili posrednu, za štete proizašle iz bilo koje aktivnosti  \n" +
"\n" +
"Korisnika u provedbi ugovorenog projekta. \n" +
"\n" +
" \n" +
"\n" +
"Članak 16. \n" +
"\n" +
"Potpisom ovog ugovora Korisnik se obvezuje da kao korisnik bespovratnih sredstava iz javnih izvora za \n" +
"\n" +
" provođenje projekta od interesa za opće dobro neće sudjelovati u izbornoj ili drugoj promidžbi  \n" +
"\n" +
"političke stranke, koalicije ili kandidata, neće davati izravnu potporu političkoj stranci, koaliciji \n" +
"\n" +
" ili kandidatu niti prikupljati financijska sredstva za financiranje političkih stranaka, koalicija  \n" +
"\n" +
"ili kandidata za sve vrijeme trajanja ovog ugovora. \n" +
"\n" +
" \n" +
"\n" +
"Članak 17. \n" +
"\n" +
"U slučaju da se spor u provedbi ovog ugovora između Ministarstva i Korisnika ne može riješiti  \n" +
"\n" +
"sporazumno, niti mirenjem, spor rješava stvarno nadležan sud u Zagrebu. \n" +
"\n" +
" \n" +
"\n" +
"Članak 18. \n" +
"\n" +
"Na elemente financiranja projekta koji nisu uređeni ovim ugovorom na odgovarajući se način  \n" +
"\n" +
"primjenjuju Opći uvjeti propisani člancima 37. do 50. i 52. do 54. Uredbe o kriterijima, mjerilima \n" +
"\n" +
" i postupcima financiranja i ugovaranja programa i projekata od interesa za opće dobro koje provode  \n" +
"\n" +
"udruge („Narodne novine“ broj 26/15, 37/21). \n" +
"\n" +
" \n" +
"\n" +
"Članak 19. \n" +
"\n" +
"Obrazac opisa projekta i Obrazac proračuna projekta koje je Korisnik dostavio prijavljujući se na  \n" +
"\n" +
"natječaj, sastavni su dio ovog ugovora te čine njegove Priloge 1 i 2. \n" +
"\n" +
" \n" +
"\n" +
"Članak 20. \n" +
"\n" +
"Za svaki oblik komunikacije (dostavu obavijesti o izmjenama i dopunama ugovora, dostavu izvještaja \n" +
"\n" +
" i sl.) koji je povezan s ovim ugovorom potrebno je navesti klasu, urudžbeni broj ugovora i naziv  \n" +
"\n" +
"projekta te ga poslati na slijedeću adresu: \n" +
"\n" +
"za davatelja: Ministarstvo turizma i sporta, Prisavlje 14, Zagreb; e-mail: udruge@mints.hr, \n" +
"\n" +
"za korisnika: <ime> <prezime> , e-mail: <email>. \n" +
"\n" +
" \n" +
"\n" +
"Članak 21. \n" +
"\n" +
"Ovaj ugovor sastavljen je u tri (3) istovjetna primjerka, od kojih jedan (1) primjerak zadržava \n" +
"\n" +
" Korisnik, a dva (2) primjerka Ministarstvo. \n" +
"\n" +
" \n" +
"\n" +
"Članak 22. \n" +
"\n" +
"Ovaj ugovor stupa na snagu s danom kad ga potpiše posljednja ugovorna strana.  \n" +
"\n" +
" \n" +
"\n" +
" \n" +
"\n" +
" \n" +
"\n" +
"ZA KORISNIKA 		ZA MINISTARSTVO \n" +
"\n" +
"<ime> <prezime>                       Ministrica dr.sc. Nikolina Brnjac \n" +
"\n" +
" \n" +
"\n" +
" \n" +
"__________________________	      __________________________ \n" +
"\n" +
"\n" +
" \n" +
"\n" +
" \n" +
"\n" +
" \n" +
"KLASA:		 \n" +
"\n" +
"URBROJ:	 \n" +
"\n" +
" \n" +
"\n" +
"Prilozi: \n" +
"\n" +
"- Obrazac opisa projekta (Prilog 1) \n" +
"\n" +
"- Obrazac proračuna projekta (Prilog 2) \n" +
"\n" +
" ");
        }
if(itemText.equals("dokument2")){
 txtPolje.setText("MINISTARSTVO PODUZETNIŠTVA I OBRTA, OIB: 53478826580, Ulica grada Vukovara 78, 10000\n" +
"Zagreb, zastupano po Darku Horvatu, ministru (u daljnjem tekstu: Ministarstvo) i\n" +
"<ime> <prezime>, OIB: <oib>, <adresa> <kucniBroj> (u daljnjem tekstu: Korisnik), zastupan\n" +
" po zakonskom zastupniku/roditelju ili skrbniku, zaključuju\n" +
"\n" +
"\n" +
"UGOVOR O DODJELI BESPOVRATNE POTPORE\n" +
"UGOVOR br. <brojUgovora>\n" +
"\n" +
"\n" +
"Članak 1.\n" +
"\n" +
"Ovim Ugovorom uređuju se međusobna prava i obveze ugovornih strana u vezi dodjele \n" +
"bespovratne potpore odobrene u okviru Otvorenog javnog poziva za Projekt „Stipendiranje \n" +
"učenika u obrtničkim zanimanjima“, KLASA: 311-01/16-01/172, URBROJ: 516-04-02-01-02/1-15-18 \n" +
"od 1. kolovoza 2016. godine (dalje u tekstu: Javni poziv).\n" +
"\n" +
"\n" +
"\n" +
"Članak 2.\n" +
"\n" +
"Ovim Ugovorom Ministarstvo dodjeljuje Korisniku poticajna, namjenska i bespovratna sredstva\n" +
" u najvišem iznosu do <cijena> kn (slovima: <cijenaSlovima>) (u daljnjem tekstu: odobrena \n" +
"sredstva) za stipendiju učeniku koji se obrazuje za deficitarno obrtničko zanimanje, pod \n" +
"uvjetima i sukladno kriterijima navedenim u Javnom pozivu i ovom Ugovoru, a za sufinanciranje \n" +
"koje je Korisnik prijavio na temelju Javnog poziva.\n" +
"\n" +
"Mjesečni iznos stipendije iznosi 750,00 kn (sedamstopedeset kuna) te je navedeni iznos \n" +
"Korisnik dužan namjenski koristiti za školovanje. \n" +
"\n" +
"\n" +
"\n" +
"Članak 3.\n" +
"\n" +
"Korisnik se obvezuje redovito savladavati propisano školsko gradivo bez ponavljanja razreda, \n" +
"a Ministarstvo se obvezuje isplaćivati stipendiju u razdoblju od 1. rujna 2016. \n" +
"(prvog rujna dvijetisućešesnaeste) do 31. kolovoza 2017. (tridesetprvog kolovoza dvijetisućesedamnaeste) \n" +
"godine.\n" +
"\n" +
"\n" +
"\n" +
"Članak 4.\n" +
"\n" +
"Odobrena sredstva iz članka 2. ovog Ugovora isplaćuju se u dva obroka:\n" +
"I razdoblje: rujan - prosinac 2016. godine,\n" +
"II razdoblje: siječanj - kolovoz 2017. godine.\n" +
"\n" +
"Prvi dio odobrenih sredstava isplatiti će se na žiro-račun Korisnika broj <iban> nakon što \n" +
"Korisnik dostavi Ministarstvu potpisani Ugovor i ispunjeni Obrazac 1. „Podaci o sudionicima“ i \n" +
"to u roku od 15 radnih dana od dana zaprimanja istih u Ministarstvu.\n" +
"Drugi dio odobrenih sredstava isplatiti će se u tijeku prvog kvartala 2016. godine.\n" +
" \n" +
"Prije isplate, Ministarstvo će izvršiti provjeru da li je žiro-račun Korisnika u blokadi te u \n" +
"slučaju utvrđenja blokade računa, Ministarstvo neće izvršiti isplatu i oslobađa se obveze isplate odobrenih sredstava.\n" +
"\n" +
"\n" +
"\n" +
"Članak 5.\n" +
"\n" +
"Korisnik se obvezuje, pismeno izvijestiti Ministarstvo o svim promjenama relevantnim za odredbe \n" +
"ovoga Ugovora (adresa prebivališta, dugotrajna bolest, ispis iz škole, ponavljanje razreda i slično) \n" +
"u roku od 30 dana od nastale promjene.\n" +
"\n" +
"Ukoliko Korisnik bez opravdanog razloga ne ispuni obavezu iz stavka 1. ovoga članka, gubi pravo \n" +
"na stipendiju te je isti dužan vratiti do tada primljeni iznos stipendije.\n" +
"\n" +
"U trenutku potpisivanja ovog Ugovora kao i za vrijeme trajanja istog, Korisnik ne smije biti \n" +
"primatelj niti jedne druge stipendije ili kredita kao pomoć za školovanje.\n" +
"Ukoliko Korisnik u trenutku potpisivanja ovog Ugovora kao i za vrijeme trajanja istog, primi \n" +
"stipendiju ili kredit, gubi pravo na stipendiju te je dužan vratiti do tada primljeni iznos stipendije.\n" +
"\n" +
"Korisnik je dužan u roku od 30 dana od dana završetka školske godine, odnosno najkasnije do 30. rujna 2017. \n" +
"godine Ministarstvu dostaviti dokaz o opravdanosti korištenja sredstava (svjedodžba) i ispunjeni Obrazac \n" +
"2. „Podaci nakon završetka aktivnosti“.\n" +
"Ispunjenje obveze u navedenom roku je bitan sastojak Ugovora.\n" +
"\n" +
"Zahtjev Korisnika za produljenje ugovorenog roka za dostavu dokaza o namjenskom utrošku dodijeljenih \n" +
"sredstava Ministarstvu može se podnijeti najkasnije 30 dana prije isteka ugovorenog roka, u suprotnom \n" +
"se neće uzeti u razmatranje.\n" +
"\n" +
"Na pisani zahtjev Korisnika, Ministarstvo može, kada za to postoje objektivno opravdani razlozi, \n" +
"produljiti rok iz stavka 2. ovog članka.\n" +
"\n" +
"U slučaju da Korisnik ne postupi sukladno stavcima 2., 3., 4. i 5. ovog članka, Ugovor će se smatrati \n" +
"raskinutim te će se u tom slučaju primijeniti članak 7. ovog Ugovora.\n" +
"\n" +
"\n" +
"\n" +
"\n" +
"Članak 6.\n" +
"\n" +
"U svrhu provođenja kontrole namjenskog korištenja sredstava Ministarstvo poduzetništva i obrta \n" +
"je ovlašteno izvršiti provjeru korištenja odobrenih sredstava uvidom u dokumentaciju na temelju \n" +
"koje je ostvarena potpora.\n" +
"\n" +
"Potpisom ovog Ugovora, Korisnik daje izričitu suglasnost Ministarstvu da može u bilo kojem \n" +
"trenutku izvršiti uvid u statusnu i svu drugu dodatnu dokumentaciju koja se odnosi na Korisnika \n" +
"i Projekt, a u svrhu provjere realizacije iste i istinitosti podataka koje je Korisnik naznačio \n" +
"u Prijavnom obrascu STIPENDIRANJE/2016 i izjavama koje je priložio uz Prijavni obrazac \n" +
"STIPENDIRANJE/2016. Korisnik se obvezuje na zahtjev Ministarstva dostaviti traženu dokumentaciju.\n" +
"\n" +
"U slučaju da Korisnik ne omogući Ministarstvu provedbu kontrole namjenskog korištenja sredstava, \n" +
"dužan je izvršiti povrat isplaćenih sredstava s pripadajućim zakonskim zateznim kamatama u korist \n" +
"Državnog proračuna na način i u roku utvrđenom u članku 7. stavku 1. ovog Ugovora.\n" +
"\n" +
"\n" +
"\n" +
"Članak 7.\n" +
"\n" +
"U slučaju da Ministarstvo utvrdi nenamjensko korištenje sredstava, kao i u slučaju da Ministarstvo\n" +
" naknadnom provjerom utvrdi drugačije stanje u odnosu na ono koje je bilo osnova za odobrenje\n" +
" \n" +
"sredstava iz članka 2. ovog Ugovora, tj. ako Ministarstvo utvrdi da podaci iz Prijavnog obrasca \n" +
"STIPENDIRANJE/2016 koje je unio Korisnik te podaci iz izjava koje je Korisnik potpisao i priložio uz \n" +
"Prijavni obrazac STIPENDIRANJE/2016 ne odgovaraju stanju koje je Ministarstvo utvrdilo naknadnom \n" +
"provjerom u dokumentaciji i/ili na terenu, Korisnik je obvezan isplaćena sredstva s pripadajućim \n" +
"zakonskim zateznim kamatama vratiti u Državni proračun Republike Hrvatske u roku od 15 dana od dana \n" +
"zaprimanja Odluke o povratu sredstava.\n" +
"Zakonska zatezna kamata će se računati od dana primitka isplate.\n" +
"Ukoliko se dostava Odluke o povratu sredstava na adresu Korisnika iz ovog Ugovora ne obavi, dostava \n" +
"odluke se smatra obavljenom istekom osmoga dana od stavljanja pismena na oglasnu ploču Ministarstva.\n" +
"\n" +
"Ako se utvrdi nenamjensko korištenje sredstava, Korisnik će biti uvršten na popis korisnika koji \n" +
"nisu namjenski koristili sredstva a koji će biti javno objavljen na mrežnim stranicama Ministarstva \n" +
"poduzetništva i obrta.\n" +
"\n" +
"\n" +
"\n" +
"Članak 8.\n" +
"\n" +
"Potpisom ovog Ugovora Korisnik se obvezuje na izvršenje svih obveza predviđenih u Javnom pozivu\n" +
" i sve obveze iz ovog Ugovora.\n" +
"\n" +
"Ministarstvo će jednostrano raskinuti Ugovor ukoliko Korisnik iz bilo kojeg razloga prestane \n" +
"izvršavati obvezu iz točke 1. ovoga članka.\n" +
"\n" +
"Ovim Ugovorom Ministarstvo pridržava pravo na povrat sredstava isplaćenih na ime stipendije u \n" +
"slučaju da Korisnik redovito ne savladava propisano školsko gradivo bez ponavljanja razreda.\n" +
"Korisnik koji ponavlja razred gubi pravo na stipendiju te je dužan vratiti do tada primljeni iznos stipendije.\n" +
"\n" +
"Ukoliko Korisnik napusti ili prekine školovanje, svojevoljno ili po izrečenoj stegovnoj mjeri, \n" +
"Ministarstvo će raskinuti Ugovor te je dužan vratiti cjelokupni primljeni iznos stipendije.\n" +
"\n" +
"\n" +
"\n" +
"Članak 9.\n" +
"\n" +
"Jedan potpisani primjerak Ugovora Korisnik je dužan dostaviti Ministarstvu u roku od 15 dana \n" +
"od primitka ovog Ugovora.\n" +
"\n" +
"Ovaj Ugovor neće imati pravni učinak niti će obvezivati Ministarstvo, ukoliko Korisnik u roku iz \n" +
"stavka 1. ovog članka ne dostavi Ministarstvu potpisani primjerak Ugovora.\n" +
"U navedenom slučaju smatrati će se da je Korisnik odustao od prijave za dodjelu sredstava.\n" +
"\n" +
"\n" +
"\n" +
"Članak 10.\n" +
"\n" +
"Korisnik potpisom ovog Ugovora daje pristanak da Ministarstvo prikuplja, obrađuje i koristi podatke\n" +
" iz ovog Ugovora, kao i podatke iz cjelokupne suradnje ostvarene s Korisnikom u svrhu promidžbenih \n" +
"aktivnosti Ministarstva poduzetništva i obrta te pristaje na sudjelovanje u medijskom praćenju provedbe\n" +
" Projekta (intervju, snimanje i sl.).\n" +
"\n" +
"Korisnik svojim potpisom ovog Ugovora pristaje na javnu objavu svojih podataka te objavu podataka \n" +
"iz članka 7. stavak 3. ovog Ugovora.\n" +
"\n" +
"\n" +
" \n" +
"Članak 11.\n" +
"\n" +
"Stranke će sve eventualne sporove rješavati sporazumno.\n" +
"U slučaju da se ne postigne sporazum, ugovara se nadležnost stvarno nadležnog suda u Zagrebu.\n" +
"\n" +
"Članak 12.\n" +
"\n" +
"Ovaj Ugovor stupa na snagu danom kad ga potpišu obje strane.\n" +
"Ovaj Ugovor sastavljen je u 2 (dva) primjerka, od kojih svaka ugovorna strana zadržava po 1 (jedan) \n" +
"primjerak.\n" +
"\n" +
"\n" +
"ZA MINISTARSTVO		ZA KORISNIKA\n" +
"ministar			roditelj/staratelj\n" +
"\n" +
" \n" +
"Darko Horvat			(ime i prezime)\n" +
"\n" +
"\n" +
"______________________		________________________\n" +
"\n" +
"\n" +
"\n" +
"Datum potpisa:			Datum potpisa:\n" +
"");
  
}       
    }//GEN-LAST:event_btnDohvatiActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDohvati;
    private javax.swing.JComboBox<String> comboIzaberi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtPolje;
    // End of variables declaration//GEN-END:variables
}
